/**
 * PlanCard — Type Definitions
 *
 * @see docs/orchestration/06-technical-specifications.md (Component 1)
 */

import { PlanStep } from '../../types/common';

export interface PlanCardProps {
  /** Title of the plan */
  title: string;

  /** Array of plan steps to display */
  steps: PlanStep[];

  /** Plan mode — determinate (known total) or indeterminate */
  mode?: 'determinate' | 'indeterminate';

  /** Assumptions the agent made */
  assumptions?: string[];

  /** Agent's overall reasoning for this plan */
  reasoning?: string;

  /** Override which step appears active (by step ID) */
  activeStepId?: string;

  /** Called when a step is clicked */
  onStepClick?: (step: PlanStep) => void;

  /** Show confidence per step */
  showConfidence?: boolean;

  /**
   * When true, indicates that plan steps are still being generated by a
   * streaming backend. Exposes `data-streaming="true"` on the root element
   * as a CSS hook — the consumer decides how to style the streaming state.
   */
  isStreaming?: boolean;

  /**
   * Global toggle for per-step reasoning text. Defaults to `false` — reasoning
   * is hidden unless explicitly opted in. Requires `PlanStep.reasoning` to be
   * populated to have any effect.
   */
  showReasoning?: boolean;

  /**
   * ID of the step whose reasoning is expanded by default (uncontrolled).
   * Follows the same pattern as `activeStepId`. No-op if `showReasoning` is
   * false or the step has no `reasoning` string.
   */
  defaultExpandedStepId?: string;

  /** Additional CSS class */
  className?: string;
}
